### ISSUE TITLE
When first dropping a calendar widget in active widgets sidebar select2 calendar id dropdown can't be opened

### ISSUE THREAD

**Issue by nekojira** [moonstonemedia/WP-Google-Calendar-Events#51]
The dropdown for selecting a calendar in widget uses select2() to enhance the standard select input dropdown. This works and select2() is correctly initialized on the target element.

However, when a new calendar is just dropped in the right sidebar of active widgets, the select2 input is not clickable. Probably related to height calculations of original container? Original visibility of container?

It will work after it is saved and page is refreshed, even if the accordions in active widgets sidebar are collapsed. But users can't select a calendar when immediately added and might think it's a bug.

**Comment by nekojira** [comment]
https://github.com/moonstonemedia/WP-Google-Calendar-Events/blob/refactor/includes/widgets/calendar.php#L174

**Comment by nekojira** [comment]
@nickyoung87  probably a solution here would be to reinitialize select2() after the current widget (not any) is dropped in active widget sidebar. 

select2() can be reinitialized by calling destroy() on the previous instance and then reapplying it with the same args.

haven't found yet a right trigger for this

`
$( 'div.widgets-sortables' ).bind( 'sortstop', function( event, ui ) {
    console.log( 'just dropped in' );
});
`
this doesn't work well for example, as it would trigger on each dropped widget

**Comment by nekojira** [comment]
the inline js referenced [before[(https://github.com/moonstonemedia/WP-Google-Calendar-Events/issues/51#issuecomment-136364172) was removed and now using only this script: https://github.com/moonstonemedia/WP-Google-Calendar-Events/blob/refactor/assets/js/gce-admin-add-calendar.js#L8 - which is also shared with the 'attach calendar' meta box (to attach calendars to post content without shortcodes).

The problem here is that I can't find a good trigger or a good way to init select2() when a calendar is added to `#widgets-right` active widgets area. It needs to be triggered after the clone from the drag and drop is in place (the calendar widget has been dragged in active widgets area) and ideally the drawer open.

I'd be open to all solutions except those that involve setTimeout().

**Comment by nickyoung87** [comment]
@nekojira What do you think of this?

```php
$(document).ajaxStop(function() {
			$( '.gce-field-select-enhanced' ).each( function( e, i ) {

				var field = $(i),
					noResults = field.data( 'noresults' ),
					allowClear = field.data( 'allowclear' );

				field.select2({
					allowClear     : allowClear != 'undefined' ? allowClear : false,
					placeholder    : {
						id         : '',
						placeholder: ''
					},
					dir            : gce_admin.text_dir != 'undefined' ? gce_admin.text_dir : 'ltr',
					tokenSeparators: [','],
					width          : '100%',
					language       : {
						noResults: function() {
							return noResults != 'undefined' ? noResults : '';
						}
					}
				} );
			} );
		});
```

**Comment by nekojira** [comment]
thanks will look further on ajaxStop

the widgets page prints already every widget form markup in  the left sidebar (the pool of widgets to choose from). When you drag a widget into the right sidebar (active widgets area) jQuery clones the html of the widget from the left to the right sidebar. With cloning, allows the user to create multiple instances of the widget (that's also why you have that weird __i__ in the counter - for inactive widgets, the counter is only initialized when the widget is copied and becomes active).

Select2() probably gets initialized twice or it's cloned twice

**Comment by nickyoung87** [comment]
@nekojira What I was thinking is that the actual ajaxStop gets called more than once. So maybe there is a way to run it only one time and then default to another way? Not sure if we can remove that handler somehow after using it. And then it becomes a problem again if the page is refreshed I think.

**Comment by nickyoung87** [comment]
@nekojira Please test my commit when you have a chance and see if it works out well for you.

**Comment by nekojira** [comment]
cool thanks!

**Comment by nekojira** [comment]
very good

I have manually included the changes in the main refactor branch, you can either update or remove your branch to move further

thanks
