### ISSUE TITLE
Replace ThickBox with Magnific Popup

### ISSUE THREAD

**Issue by unfulvio** [moonstonemedia/WP-Google-Calendar-Events#53]
in 2.x and 3.x the Add Shortcode button uses ThickBox which comes preloaded in WordPress edit post pages as it's used by the Media Uploader. 

ThickBox is old as a dinosaur and it has been mangled for internal WordPress purposes anyway. A lot of people writing media buttons hack ThickBox to add buttons next to `Add Media` button in the Editor.

Not urgent, but in future it'd be better to replace this with another modal and lightweight jQuery plugin, perhaps Magnific Popup.

**Comment by pderksen** [comment]
Looks like a great library. I already had it starred and it's obviously popular. If it's easier to work with a lighter weight then go for it.
