### ISSUE TITLE
Change Template

### ISSUE THREAD

**Issue by zhengphor** [moonstonemedia/WP-Google-Calendar-Events#56]
Hi,

could be I don't find it, but even though I went through your Code I haven't found a way where you implement which wp-template is used to display the events. I would like to use a different template so if you could tell me how this would be possible or even integrate that in a upcoming version I would be delighted.

**Comment by nekojira** [comment]
Hello @zhengphor 

at the moment this is only done via the WordPress editor. When you edit a feed post type you can actually use tags and html. 

here's a list of the current available tags http://wpdocs.philderksen.com/google-calendar-events/event-builder/

personally I'd like having this replaced by a 'visual builder' so people don't need to use these shortcode-like tags - but we need to account for people already using this system

I am also thinking if it's the case to have a WordPress template file to override all this

if you are interested to the changes ahead, have a look at the refactor branch of this repository which contains a new version (warning do not use it in a  production site yet or it may break things)
