### ISSUE TITLE
feature request - day of week

### ISSUE THREAD

**Issue by skwechter** [moonstonemedia/WP-Google-Calendar-Events#57]
Any way to add the day of the week to the display? 
"Friday, September 11"

**Comment by nekojira** [comment]
you can currently use `date format` setting either among the postmeta or in a `format` tag attribute

more docs here: http://wpdocs.philderksen.com/google-calendar-events/

please use the plugin support forums on WordPress.org https://wordpress.org/support/plugin/google-calendar-events for support  or feature requests and use GitHub issues for code issues or code modifications 

thank you
